---
    - name: Apply traffic isolation tasks
      ansible.builtin.include_role:
        name: role-juniper-traffic-redirect
      vars:
        _isolate_: true
        _normalize_: false
        _ospf_cmds_: "{{ ospf_isolation_cmds_list }}"    # List of commands to change OSPF
        _bgp_cmds_: "{{ bgp_isolation_cmds_list }}"      # List of command to change BGP
        _vrrp_cmds_: "{{ lookup('file', '{{ vrrp_isolate }}').splitlines() }}"    # List of commands to change vrrp
        _interfaces_cmds_: "{{ lookup('file', '{{ disable_intfcs }}').splitlines() }}" # list of commands to change interfaces



---
    - name: Apply traffic normalization tasks
      ansible.builtin.include_role:
        name: role-juniper-traffic-redirect
      vars:
        _isolate_: false
        _normalize_: true
        _ospf_cmds_: "{{ ospf_normalization_cmds_list }}"
        _bgp_cmds_: "{{ bgp_normalization_cmds_list }}"
        _vrrp_cmds_: "{{ lookup('file', '{{ vrrp_normalize }}').splitlines() }}"
        _interfaces_cmds_: "{{ lookup('file', '{{ enable_intfcs }}').splitlines() }}"
