---
# Configure device
- name: "Display command for - {{ _stage_ }}"
  ansible.builtin.debug:
    var: _cmds_list_
  delegate_to: localhost

- name: "Apply configuration changes - {{ _stage_ }}"
  junipernetworks.junos.junos_config:
    lines: "{{ _cmds_list_ }}"
    comment: "implementing {{ _stage_ }} traffic redirection"
  ignore_errors: true


