---
# Configure device
- name: "Display command for - {{ stage }}"
  ansible.builtin.debug:
    var: _cmds_list_
  delegate_to: localhost
  ignore_erros: true

# - name: "Apply configuration changes - {{ stage }}"
#   junipernetworks.junos.junos_config:
#     lines: "{{ _cmds_list_ }}"
#     comment: "implementing {{ stage }} traffic redirection"
#   ignore_errors: true


