---
# Configure device
- name: Display applied commands (for verification)
  ansible.builtin.debug:
    var: _cmds_list_
  delegate_to: localhost

# - name: Configure device
#   junipernetworks.junos.junos_config:
#     lines: "{{ _cmds_list_ }}"
#     comment: "implementing {{ stage }} traffic redirection"
#   ignore_errors: true


