---
# Common git tasks for traffic redirection
- name: "Git pull {{ network_config_backup_gitlab_repo }}"
  ansible.builtin.include_role:
    name: role-gitlab
  vars:
    _git_: true
    _clone_: true
    _upload_: false
    _git_repo_: "{{ network_config_backup_gitlab_repo }}"
    _git_repo_branch_: "{{ network_config_backup_gitlab_repo_branch }}"
    _git_namespace_: "{{ gitlab_namespace }}"
    _git_user_: "{{ gitlab_user }}"
    _git_token_: "{{ gitlab_user_token }}"
    _git_email_: "{{ gitlab_user_email }}"
    _tmp_root_dir_: "{{ tmp_base_dir }}"
    _remote_git_dir_: false
    _local_file_path_: false  # path to file that is to be uploaded
 
# Creating this outside the role-gitlab so as to create the config files directly into the local git repo.
# No need to copy from tmp_root_dir into the git_dir_path again.
- name: Ensure git_traffic_redirect_subdir_path is present - create if absent
  ansible.builtin.file:
    path: "{{ tmp_base_dir }}/{{ git_traffic_redirect_subdir_path }}"
    state: directory
  ignore_errors: true
  delegate_to: localhost
  when: prep_config