---
# southbound interfaces traffic movement
- name: SOUTHBOUND INTERFACES - Display applied commands (for verification)
  ansible.builtin.debug:
    var: _interfaces_cmds_
  delegate_to: localhost

# - name: Implement southbound interfaces traffic redirection
#   junipernetworks.junos.junos_config:
#     lines: "{{ _interfaces_cmds_ }}"
#     comment: Implement southbound interfaces traffic redirection
#   ignore_errors: true
#   when: traffic_movement
