---
# VRRP traffic movement tasks

- name: VRRP - Display applied commands (for verification)
  ansible.builtin.debug:
    var: _vrrp_cmds_
  delegate_to: localhost

# - name: VRRP - Implement vrrp traffic redirection
#   junipernetworks.junos.junos_config:
#     lines: "{{ vrrp_commands }}"
#     comment: Implement vrrp traffic redirection
#   ignore_errors: true
#   when: traffic_movement
    

